rename "b1 copy.png" b1.png
rename "b2 copy.png" b2.png
rename "b3 copy.png" b3.png
rename "b4 copy.png" b4.png
rename "b5 copy.png" b5.png
rename "b6 copy.png" b6.png
rename "b7 copy.png" b7.png
rename "b8 copy.png" b8.png
rename "b9 copy.png" b9.png
rename "c1 copy.png" c1.png
rename "c2 copy.png" c2.png
rename "c3 copy.png" c3.png
rename "c4 copy.png" c4.png
rename "c5 copy.png" c5.png
rename "c6 copy.png" c6.png
rename "c7 copy.png" c7.png
rename "c8 copy.png" c8.png
rename "c9 copy.png" c9.png
rename "d1 copy.png" d1.png
rename "d2 copy.png" d2.png
rename "d3 copy.png" d3.png
rename "d4 copy.png" d4.png
rename "d5 copy.png" d5.png
rename "d6 copy.png" d6.png
rename "d7 copy.png" d7.png
rename "d8 copy.png" d8.png
rename "d9 copy.png" d9.png
rename "dragon-g copy.png" dragon-g.png
rename "dragon-r copy.png" dragon-r.png
rename "dragon-w copy.png" dragon-w.png
rename "flower-1 copy.png" flower-1.png
rename "flower-2 copy.png" flower-2.png
rename "flower-3 copy.png" flower-3.png
rename "flower-4 copy.png" flower-4.png
rename "season-1 copy.png" season-1.png
rename "season-2 copy.png" season-2.png
rename "season-3 copy.png" season-3.png
rename "season-4 copy.png" season-4.png
rename "wind-e copy.png" wind-e.png
rename "wind-n copy.png" wind-n.png
rename "wind-s copy.png" wind-s.png
rename "wind-w copy.png" wind-w.png
